#YAML files use a tree-like structure which helps with visualizing nested configs

#Application Settings
spring:
  application:
    name: internalAdminDashboard
#  profiles:
#    active: test NEVER SET THE TEST PROFILE AS ACTIVE WITHIN THE TEST CONFIG
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: SA
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop #Drops database after test ends
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2console
