name: Java CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test

    - name: Deploy to Prod
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: akhileshns/heroku-deploy@v3.12.12  # This is a community action for deploying to Heroku
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "springboot-loans" 
        heroku_email: "vishalmkumar3@gmail.com"
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    
